### ISSUE TITLE
installed into 3.04, picked placekitten with default setting, crashes Sketch.

### ISSUE THREAD

**Issue by BobWalsh** [tylergaw/day-player#12]

**Comment by tylergaw** [comment]
Was finally back in and looking at this. placekitten.com appears to be on it's 9th life. It no longer returns images if the `/g` portion of the url is in place. For example, this is the url the show as an example https://placekitten.com/200/300 (it does not produce an image)

This does though: https://placekitten.com/g/200/300

I'll think I'll update to https since it looks like that's what they prefer, and remove the normal/gray option and always return a gray image.
